# Generated by Django 5.2.11 on 2026-02-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_pics/')),
            ],
        ),
    ]
